name: pycdi
channels:
    - conda-forge
    - plotly
dependencies:
    - jupyter
    - notebook
    - jupyterlab
    - jupyter-book
    - ipywidgets
    - nodejs>=20,<21
    - mystmd
    - jupyterlab-myst
    - libwebp
    - gdal
    - numpy<2.0
    - scipy
    - pandas
    - matplotlib
    - plotly
    - bokeh
    - netCDF4
    - scikit-learn
    - geopandas
    - xarray
    - zarr
    - leafmap
    - localtileserver
    - pip
    - cartopy
    - pip:
      - cubo 
      
    
