name: pycdi
channels:
    - conda-forge

dependencies:
    - python=3.9
    - jupyterlab
    - ipywidgets
    - numpy<2.0
    - gdal
    - scipy
    - pandas
    - matplotlib
    - plotly
    - netCDF4
    - scikit-learn
    - geopandas
    - xarray
    - zarr
    - leafmap
    - localtileserver
    - pip
    - cartopy
    - requests
    - aiohttp
    - pip:
      - cubo 
      
    
