name: pycdi
channels:
    - conda-forge
dependencies:
    - python=3.9
    - jupyterlab
    - ipywidgets
    - nodejs=18
    - mystmd
    - jupyterlab-myst
    - libwebp
    - gdal
    - numpy<2.0
    - scipy
    - pandas
    - matplotlib
    - plotly
    - bokeh
    - netCDF4
    - scikit-learn
    - geopandas
    - xarray
    - zarr
    - leafmap
    - localtileserver
    - pip
    - cartopy
    - pip:
      - cubo 
      
    
